version: '3.5'

services:
  webserver:
    build:
      context: ./docker
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - ./file_envs:/var/www
    container_name: deolhonospoliticos
